[package]
name = "advos"
version = "0.1.0"
authors = ["Michael Goin <mgoin@vols.utk.edu>", "Jacob Rutherford <jruthe10@vols.utk.edu>"]
edition = "2018"

[profile.dev]
lto = false
panic = "abort"

[profile.release]
lto = true
panic = "unwind"

[lib]
crate-type = ["staticlib"]

[dependencies]
